-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains all types with cyclic dependencies (between each other or to itself)
module BlockfrostAPI.TypeAlias where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified BlockfrostAPI.Common
import {-# SOURCE #-} BlockfrostAPI.Types.AccountAddressesAsset
import {-# SOURCE #-} BlockfrostAPI.Types.AddressUtxoContent
import {-# SOURCE #-} BlockfrostAPI.Types.BlockContent
import {-# SOURCE #-} BlockfrostAPI.Types.EpochContent


-- | Defines an alias for the schema located at @components.schemas.pool_list@ in the specification.
-- 
-- 
type PoolList = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.pool_blocks@ in the specification.
-- 
-- 
type PoolBlocks = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.epoch_content_array@ in the specification.
-- 
-- 
type EpochContentArray = [EpochContent]

-- | Defines an alias for the schema located at @components.schemas.epoch_block_content@ in the specification.
-- 
-- 
type EpochBlockContent = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.empty_object@ in the specification.
-- 
-- 
type EmptyObject = Data.Aeson.Types.Internal.Object

-- | Defines an alias for the schema located at @components.schemas.block_content_txs@ in the specification.
-- 
-- 
type BlockContentTxs = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.block_content_array@ in the specification.
-- 
-- 
type BlockContentArray = [BlockContent]

-- | Defines an alias for the schema located at @components.schemas.asset_txs@ in the specification.
-- 
-- 
type AssetTxs = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.address_utxo_contents@ in the specification.
-- 
-- 
type AddressUtxoContents = [AddressUtxoContent]

-- | Defines an alias for the schema located at @components.schemas.address_txs_content@ in the specification.
-- 
-- 
type AddressTxsContent = [Data.Text.Internal.Text]

-- | Defines an alias for the schema located at @components.schemas.account_addresses_assets@ in the specification.
-- 
-- 
type AccountAddressesAssets = [AccountAddressesAsset]
