-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema PoolDelegator
module BlockfrostAPI.Types.PoolDelegator where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified BlockfrostAPI.Common
import BlockfrostAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.pool_delegator@ in the specification.
-- 
-- 
data PoolDelegator = PoolDelegator {
  -- | address: Bech32 encoded stake addresses
  poolDelegatorAddress :: Data.Text.Internal.Text
  -- | live_stake: Currently delegated amount
  , poolDelegatorLiveStake :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON PoolDelegator
    where toJSON obj = Data.Aeson.Types.Internal.object ("address" Data.Aeson.Types.ToJSON..= poolDelegatorAddress obj : "live_stake" Data.Aeson.Types.ToJSON..= poolDelegatorLiveStake obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("address" Data.Aeson.Types.ToJSON..= poolDelegatorAddress obj) GHC.Base.<> ("live_stake" Data.Aeson.Types.ToJSON..= poolDelegatorLiveStake obj))
instance Data.Aeson.Types.FromJSON.FromJSON PoolDelegator
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "PoolDelegator" (\obj -> (GHC.Base.pure PoolDelegator GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "address")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "live_stake"))
-- | Create a new 'PoolDelegator' with all required fields.
mkPoolDelegator :: Data.Text.Internal.Text -- ^ 'poolDelegatorAddress'
  -> Data.Text.Internal.Text -- ^ 'poolDelegatorLiveStake'
  -> PoolDelegator
mkPoolDelegator poolDelegatorAddress poolDelegatorLiveStake = PoolDelegator{poolDelegatorAddress = poolDelegatorAddress,
                                                                            poolDelegatorLiveStake = poolDelegatorLiveStake}
