module BlockfrostAPI.Types.TxMetadataLabelCborItem where
import Data.Aeson
import qualified Data.Aeson as Data.Aeson.Types.Internal
data TxMetadataLabelCborItem
instance Show TxMetadataLabelCborItem
instance Eq TxMetadataLabelCborItem
instance FromJSON TxMetadataLabelCborItem
instance ToJSON TxMetadataLabelCborItem
