-- CHANGE WITH CAUTION: This is a generated code file generated by https://github.com/Haskell-OpenAPI-Code-Generator/Haskell-OpenAPI-Client-Code-Generator.

{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE MultiWayIf #-}

-- | Contains the types generated from the schema TxMetadataLabelCborItem
module BlockfrostAPI.Types.TxMetadataLabelCborItem where

import qualified Prelude as GHC.Integer.Type
import qualified Prelude as GHC.Maybe
import qualified Control.Monad.Fail
import qualified Data.Aeson
import qualified Data.Aeson as Data.Aeson.Encoding.Internal
import qualified Data.Aeson as Data.Aeson.Types
import qualified Data.Aeson as Data.Aeson.Types.FromJSON
import qualified Data.Aeson as Data.Aeson.Types.ToJSON
import qualified Data.Aeson as Data.Aeson.Types.Internal
import qualified Data.ByteString.Char8
import qualified Data.ByteString.Char8 as Data.ByteString.Internal
import qualified Data.Functor
import qualified Data.Scientific
import qualified Data.Text
import qualified Data.Text.Internal
import qualified Data.Time.Calendar as Data.Time.Calendar.Days
import qualified Data.Time.LocalTime as Data.Time.LocalTime.Internal.ZonedTime
import qualified GHC.Base
import qualified GHC.Classes
import qualified GHC.Int
import qualified GHC.Show
import qualified GHC.Types
import qualified BlockfrostAPI.Common
import BlockfrostAPI.TypeAlias

-- | Defines the object schema located at @components.schemas.tx_metadata_label_cbor_item@ in the specification.
-- 
-- 
data TxMetadataLabelCborItem = TxMetadataLabelCborItem {
  -- | cbor_metadata: Content of the CBOR metadata
  txMetadataLabelCborItemCborMetadata :: (GHC.Maybe.Maybe Data.Text.Internal.Text)
  -- | tx_hash: Transaction hash that contains the specific metadata
  , txMetadataLabelCborItemTxHash :: Data.Text.Internal.Text
  } deriving (GHC.Show.Show
  , GHC.Classes.Eq)
instance Data.Aeson.Types.ToJSON.ToJSON TxMetadataLabelCborItem
    where toJSON obj = Data.Aeson.Types.Internal.object ("cbor_metadata" Data.Aeson.Types.ToJSON..= txMetadataLabelCborItemCborMetadata obj : "tx_hash" Data.Aeson.Types.ToJSON..= txMetadataLabelCborItemTxHash obj : GHC.Base.mempty)
          toEncoding obj = Data.Aeson.Encoding.Internal.pairs (("cbor_metadata" Data.Aeson.Types.ToJSON..= txMetadataLabelCborItemCborMetadata obj) GHC.Base.<> ("tx_hash" Data.Aeson.Types.ToJSON..= txMetadataLabelCborItemTxHash obj))
instance Data.Aeson.Types.FromJSON.FromJSON TxMetadataLabelCborItem
    where parseJSON = Data.Aeson.Types.FromJSON.withObject "TxMetadataLabelCborItem" (\obj -> (GHC.Base.pure TxMetadataLabelCborItem GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "cbor_metadata")) GHC.Base.<*> (obj Data.Aeson.Types.FromJSON..: "tx_hash"))
-- | Create a new 'TxMetadataLabelCborItem' with all required fields.
mkTxMetadataLabelCborItem :: GHC.Maybe.Maybe Data.Text.Internal.Text -- ^ 'txMetadataLabelCborItemCborMetadata'
  -> Data.Text.Internal.Text -- ^ 'txMetadataLabelCborItemTxHash'
  -> TxMetadataLabelCborItem
mkTxMetadataLabelCborItem txMetadataLabelCborItemCborMetadata txMetadataLabelCborItemTxHash = TxMetadataLabelCborItem{txMetadataLabelCborItemCborMetadata = txMetadataLabelCborItemCborMetadata,
                                                                                                                      txMetadataLabelCborItemTxHash = txMetadataLabelCborItemTxHash}
